Pod::Spec.new do |s|
  s.name             = '{{name}}'
  s.version          = '0.1.0'
  s.summary          = 'Dart bridge to the product Rust core.'
  s.description      = <<-DESC
Dart bridge to the product Rust core, generated by `dovetail bridge init`.
                       DESC
  s.homepage         = 'https://github.com/Example Org/{{name}}'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Example Org' => 'mateus.siqueira@ayzen.one' }

  s.platform         = :osx, '10.15'
  s.source           = { :path => '.' }
  s.source_files     = 'Classes/**/*'

  s.script_phase = {
    :name => 'Build Rust library',
    :script => 'sh "$PODS_TARGET_SRCROOT/../cargokit/build_pod.sh" ../rust {{name}}',
    :execution_position => :before_compile,
    :input_files => ['${BUILT_PRODUCTS_DIR}/cargokit_phony'],
    :output_files => ['${BUILT_PRODUCTS_DIR}/lib{{name}}.a'],
  }
  s.pod_target_xcconfig = {
    'DEFINES_MODULE' => 'YES',
    'OTHER_LDFLAGS' => '-force_load ${BUILT_PRODUCTS_DIR}/lib{{name}}.a',
  }
end
